<?php
echo "My name is Baboo Kumar Meghwar";
echo "<br />";
echo "My father's name is Mehandro Meghwar";
echo "<br />";
echo "My caste is Meghwar(Hindu)";
echo "<br />";
echo "I am currently Intern at HIST";
echo "<br />";
echo "I completed my Bachelor Degree from University of Sindh Jamshoro";
echo "<br />";
echo "I am from small village of Tharparkar District";
echo "<br />";
echo "I want to be a PHP Full Stack Developer in future";
echo "<br />";
echo "I am 23 years old";
echo "<br />";
echo "My HIST Id is 19938";
echo "<br />";
echo "I did my Intermdiate from Sadique Faqeer Government Boys Degree College, Mithi";
echo "<br />";
